Add adapters and viewHolders for two recycler (actors and movies) + clickListener
hristofor-alex/Movies pull request #1
Opened 2021-03-26 06:28 UTC by hristofor-alex

2021-03-26 07:27 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/OnMovieItemClicked.kt
> +interface OnMovieItemClicked {
Часто такие интерфейсы выносят внутрь того адаптера, в котором он будет дергаться, если его не планируешь нигде больше использовать помимо того одного адаптера

2021-03-26 07:38 UTC, SanchoPanchos requested changes

2021-03-26 07:38 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/model/Actor.kt
> +import androidx.annotation.DrawableRes
импорт и форматирование)

2021-03-26 07:38 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/model/Movie.kt
> +    val like: Boolean,
вместо `like`, возможно, правильнее было бы назвать `isLiked`, чуть легче тогда читается
и age у фильма тоже не совсем сходу понятно, что означает, я сперва подумал, что это возраст фильма и удивился почему он строкой и почему возраст
Потом уже увидел, что это возрастное _ограничение_, возможно название переменной `ageRestriction` или что-то похожее читалось бы легче. и почему строкой, а не `Int`?

2021-03-26 07:38 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/view/FragmentMovieDetails.kt
> +    private var movie: Movie? = null
Может ли фильм действительно быть здесь null? Возможно стоит убрать nullability у переменной и если когда мы достаем из аргументов фильм и там null, то бросать ошибку или возвращать на экран назад. Тоже самое и с ресайклером, может ли он действительно быть null на этом экране?

2021-03-26 07:38 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/view/FragmentMovieList.kt
> +    private var clickListener: OnMovieItemClicked? = null
Тоже самое, может ли recycler быть null?

2021-03-26 07:38 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/view/recyclers/ViewHolderActor.kt
> +class ViewHolderActor(itemView: View) : RecyclerView.ViewHolder(itemView) {
Если этот ViewHolder не будет использоваться где-либо кроме того самого адаптера, то его, как и всякие колбеки связанные с адаптером, выносят внутрь класса адаптера

2021-03-26 07:38 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/view/recyclers/ViewHolderMovie.kt
> +            starOne.setImageResource(R.drawable.fill_star_mini)
Посмотри на виджет RatingBar, возможно тебе подойдет и не будет такого большого when

2021-03-26 07:46 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/OnMovieItemClicked.kt
> +interface OnMovieItemClicked {
Понял, то что я наследуюсь от него в MainActivity. И создаю поле его типа в FragmentMovieList это считается что я его использую где то вне адаптера? Или это все относится к одному RV?

2021-03-26 07:48 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/model/Movie.kt
> +    val like: Boolean,
Строкой потому что там идет символ "+". Например - 13+

2021-03-26 07:52 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/view/recyclers/ViewHolderMovie.kt
> +            starOne.setImageResource(R.drawable.fill_star_mini)
Вначале пытался через него сделать, но не получилось красиво отобразить кастомные звездочки. Получилось их подставить, но выглядели очень плохо. Потому отказался, но возможно можно было и его привести к хорошему виду.

2021-03-26 07:53 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/model/Movie.kt
> +    val like: Boolean,
Да, правильнее будет подставлять только цифру, потому как только она относится к ограничению. Оно ведь всегда будет с плюсом, независимо от возраста. Или тебе понадобиться вывести только те фильмы, которые 16+, тогда уже придется делать какие-то манипуляции с переменной, откидывать последний символ, кастовать к `Int` и т.д.

2021-03-26 10:29 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/OnMovieItemClicked.kt
> +interface OnMovieItemClicked {
Перенес, в адаптер фильмов

2021-03-26 10:29 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/model/Movie.kt
> +    val like: Boolean,
Все переименовал и поменял тип на int.

2021-03-26 10:30 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/view/FragmentMovieDetails.kt
> +    private var movie: Movie? = null
Убрал null и вытянул из аргументов через элвиса. При нуле кидаю NPE. Так как такого поведения нам не надо. И если закрашится надо будет исправить)

2021-03-26 10:31 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/view/FragmentMovieList.kt
> +    private var clickListener: OnMovieItemClicked? = null
Убрал null

2021-03-26 10:31 UTC, hristofor-alex commented on app/src/main/java/ru/hristoforalex/movies/view/recyclers/ViewHolderActor.kt
> +class ViewHolderActor(itemView: View) : RecyclerView.ViewHolder(itemView) {
Перенес в адаптер

2021-03-31 14:55 UTC, SanchoPanchos commented on app/src/main/java/ru/hristoforalex/movies/view/FragmentMovieList.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
а зачем этот метод добавил?

2021-03-31 14:56 UTC, SanchoPanchos approved these changes

2021-03-31 14:56 UTC, merged